### ISSUE TITLE
Option to detect wildcard during resolving

### ISSUE THREAD

**Issue by sumgr0** [projectdiscovery/dnsprobe#12]
Hi!

First thanks for an amazingly fast probing tool.

I've noticed, that when resolving the A records, it reports the wildcard IPs as well. Is there a possibility to detect the wildcards and not list them in the output?

Thanks

**Comment by ehsandeep** [comment]
Hi @sumgr0, 

Thank you for your kind words, I'm not sure if you are aware of [shuffledns](https://github.com/projectdiscovery/shuffledns), wildcard handling is one of the key problems in subdomain enumeration and **shuffledns** aims to solve that problem, **dnsprobe** is handy and lightweight fast DNS probing utility, I can suggest you pass your list to **shuffledns**  when the wildcard is an issue for your target. 

for example:- 

```
cat subdomain.txt | shuffledns -d target.com -r resolvers.txt | dnsprobe -r cname
```

I hope this helps to solve your problem.

**Comment by ehsandeep** [comment]
Closing this one, related issue which might be useful for the context https://github.com/projectdiscovery/shuffledns/issues/29
