### ISSUE TITLE
trying to install the tool give error

### ISSUE THREAD

**Issue by 0xrishabh** [projectdiscovery/dnsprobe#17]
go: github.com/projectdiscovery/dnsprobe upgrade => v1.0.1
go: github.com/projectdiscovery/retryabledns upgrade => v1.0.4
go: golang.org/x/sys upgrade => v0.0.0-20200420163511-1957bb5e6d1f
go: golang.org/x/crypto upgrade => v0.0.0-20200423211502-4bdfaf469ed5
go: golang.org/x/net upgrade => v0.0.0-20200425230154-ff2c4b7c35a0
github.com/projectdiscovery/dnsprobe/lib
github.com/projectdiscovery/dnsprobe/lib
/home/cypher/Desktop/githubTools/go/pkg/mod/github.com/projectdiscovery/dnsprobe@v1.0.1/lib/dnsprobe.go:41:17: assignment mismatch: 2 variables but "github.com/projectdiscovery/retryabledns".New returns 1 values

**Comment by schniggie** [comment]
yep, latest commit in retryabledns [see here](https://github.com/projectdiscovery/retryabledns/commit/bb6b2b24182e4230af157706bc9aa136d67edca2) changes signature of .New and that's the reason.

**Comment by 0xrishabh** [comment]
So on my end Can I do something to fix this? @schniggie

**Comment by Mzack9999** [comment]
@cYph3r1337 - Thanks for the issue! The go modules dependencies have been updated, they were still pointing to the previous version of retryabledns. Could you confirm if now it works for you?

@schniggie Thanks a lot for the PR! I've added a correction for the signature to the same PR that updated the modules, so I'm closing yours if this is solved.

**Comment by Mzack9999** [comment]
Closing as a result of #19
