### ISSUE TITLE
Custom Resolvers not working.

### ISSUE THREAD

**Issue by maverickNerd** [projectdiscovery/dnsprobe#26]
I got some resolvers from dnsvalidator, same resolvers works with shuffldns but when I pass those resolvers to dnsprobe, it shows 0 or sometime 1 domain, if I recursively run dnsprobe.

$ cat domains.txt | dnsprobe -s tools/dnsvalidator/resolvers.txt | wc -l

       __                            __
  ____/ /___  _________  _________  / /_  ___
 / __  / __ \/ ___/ __ \/ ___/ __ \/ __ \/ _ \
/ /_/ / / / (__  ) /_/ / /  / /_/ / /_/ /  __/
\__,_/_/ /_/____/ .___/_/   \____/_.___/\___/
               /_/

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
0 

Also, I tried taking default list of resolvers from the dnsprobe.go file, and provided those as input, it worked then but with dnsvalidator or "bass" tool resolvers it doesn't work.

**Comment by ehsandeep** [comment]
This is something already pointed out in discord channel, I will confirm and we will get it fixed, thanks @maverickNerd

**Comment by ehsandeep** [comment]
@maverickNerd, we fixed this in the latest version of dnsprobe, i.e [dnsx](https://github.com/projectdiscovery/dnsx), closing this issue now.
