### ISSUE TITLE
Option to only use the wildcard detection part of ShuffleDNS

### ISSUE THREAD

**Issue by Pxmme** [projectdiscovery/dnsprobe#27]
Hi team!

I noticed that there isn't any option to skip the massdns scan when starting ShuffleDNS. It would be an amazing feature since I don't need this massdns scan but I'm very interested to use the wildcard detection part of ShuffleDNS as a standalone feature.

Do you think that would be possible?

Thanks in advance :)

**Comment by ehsandeep** [comment]
@Pxmme we did it :D dnsprobe v2 == dnsx, we added this feature in [dnsx](https://github.com/projectdiscovery/dnsx), so closing this issue now.
