### ISSUE TITLE
File Output -o flag is not working

### ISSUE THREAD

**Issue by remonsec** [projectdiscovery/dnsprobe#29]
Hello 
I am not able to get any output from -o flag. 
Can you please let me know where i am doing the mistake 

Please check the recording 
https://asciinema.org/a/7ETNXijX77dgAPwzT9Ath7M4t

Thanks

**Comment by ehsandeep** [comment]
Hey @remonsec, 

Because you are using multiple values for `r` flag, where the expected value is only one, remove that extra flag and it will work. 

`-r A` or `-r CNAME`, not `-r A CNAME`
